### ISSUE TITLE
P values and Confidence Interval with adjustments `sidak` are not coherent for `plot()` and `summary()`

### ISSUE THREAD

**Issue by guilhermeparreira** [rvlenth/emmeans#230]
Hi there. My point is just a continuation from #228: 
I still have the same "messy data". I have a model with a interaction between two factors. And I want to plot it and summarize into tables. So:

```
library(emmeans)
library(ggplot2)
library(knitr)
d1 <- structure(list(tipo = c("digital", "digital", "digital", "digital", 
"digital", "digital", "digital", "digital", "digital", "digitalized", 
"digitalized", "digitalized", "digitalized", "digitalized", "digitalized", 
"digitalized", "digitalized", "digitalized", "incumbents", "incumbents", 
"incumbents", "incumbents", "incumbents", "incumbents", "incumbents", 
"incumbents", "incumbents"), categoria = c("Advice", "Digital banks", 
"Exchange", "FinTech", "Insurance", "Investments", "Lending", 
"Others", "Payments and transfers", "Advice", "Digital banks", 
"Exchange", "FinTech", "Insurance", "Investments", "Lending", 
"Others", "Payments and transfers", "Advice", "Digital banks", 
"Exchange", "FinTech", "Insurance", "Investments", "Lending", 
"Others", "Payments and transfers"), Total = c(63, 459, 279, 
63, 36, 108, 567, 9, 549, 63, 459, 279, 63, 36, 108, 567, 9, 
549, 35, 255, 155, 35, 20, 60, 315, 5, 305), Frequencia = c(33, 
64, 0, 13, 4, 2, 10, 1, 87, 44, 272, 108, 4, 11, 49, 139, 2, 
251, 27, 231, 137, 0, 20, 55, 301, 5, 244), Perc = c(52.38, 13.94, 
0, 20.63, 11.11, 1.85, 1.76, 11.11, 15.85, 69.84, 59.26, 38.71, 
6.35, 30.56, 45.37, 24.51, 22.22, 45.72, 77.14, 90.59, 88.39, 
0, 100, 91.67, 95.56, 100, 80), Failure = c(30, 395, 279, 50, 
32, 106, 557, 8, 462, 19, 187, 171, 59, 25, 59, 428, 7, 298, 
8, 24, 18, 35, 0, 5, 14, 0, 61)), class = "data.frame", row.names = c(NA, 
-27L))
mcomp <- glm(cbind(Frequencia, Failure) ~ tipo*categoria,
             data = d1, family = binomial(link = "logit"))
l1 <- emmeans(mcomp, ~tipo|categoria)
# Using sidak adjustment method
summary(l1, infer = c(T,F), 
        type = "response", adjust = "sidak")
# Just two examples:
categoria = Advice:
 tipo               prob       SE           df asymp.LCL asymp.UCL
 digital           0.52381 0.062923 Inf   0.37589   0.66767
 digitalized    0.69841 0.057822 Inf   0.54594   0.81686
 incumbents  0.77143 0.070978 Inf   0.56347   0.89822

categoria = Others:
 tipo              prob           SE         df asymp.LCL asymp.UCL
 digital           0.11111   0.104757 Inf   0.00983   0.61138
 digitalized     0.22222 0.138580 Inf   0.04042   0.65964
 incumbents  1.00000  0.000001 Inf   0.00000   1.00000

```
 It works fine. All asymptotic intervals are between 0 and 1 (I know that they could go away from this boundaries, but it didn't happen here). 

**Problem 1:** When I plot these results, the intervals changes (Have a look deeper into the category Others, which there are intervals below 0):

```
plot(l1, 
     type = "response",
     comparison = T,
     adjust = "sidak",
     int.adjust = "sidak") +
  facet_wrap(~categoria, strip.position = "right", ncol = 1,
             labeller = label_wrap_gen(width = 10)) +
  labs(x = "Probability",
       y = "Bank type")
```
![image](https://user-images.githubusercontent.com/13880005/94995403-6abc4280-0574-11eb-8723-0cc4f23ea4d9.png)

**Problem 2:** Moreover, If I look into the graphic the service category `Advice`, I see that `digital` differs from `incumbents`. However, when I print the comparison table, this is not the case:
```
summary(pairs(l1), infer = c(T,T), 
        type = "response", adjust = "sidak")
# Just one example:
categoria = Advice:
 contrast                     odds.ratio       SE  df asymp.LCL asymp.UCL z.ratio p.value
 digital / digitalized                  0 0.00e+00 Inf   0.19502         1  -1.997 0.1313 
 digital / incumbents                0 0.00e+00 Inf   0.10483         1  -2.360 0.0538 
 digitalized / incumbents            1 0.00e+00 Inf   0.21437         2  -0.773 0.8239 
```

**Problem 3:** Furthermore, the odds.ratio calculated becomes bizarre (I can calculate them, and the graphic plots it).

I will be happy if you could take a look on it.

**Comment by rvlenth** [comment]
This is kind of a thorny issue -- known already to at least me. If you have `comparisons = TRUE`, we are forced to re-grid the object because it just gets too hard to think about how to construct the comparison arrows. So the display is based on:
```r
> summary(regrid(l1), infer = c(T,F), adjust = "sidak")
. . .

categoria = Others:
 tipo             prob         SE  df  asymp.LCL asymp.UCL
 digital     0.1111111 0.10475656 Inf -0.1390201 0.3612423
 digitalized 0.2222222 0.13857990 Inf -0.1086703 0.5531147
 incumbents  1.0000000 0.00000077 Inf  0.9999982 1.0000018

categoria = Payments and transfers:
 tipo             prob         SE  df  asymp.LCL asymp.UCL
 digital     0.1584699 0.01558555 Inf  0.1212557 0.1956842
 digitalized 0.4571949 0.02126114 Inf  0.4064289 0.5079609
 incumbents  0.8000000 0.02290393 Inf  0.7453114 0.8546886

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
```
Here, the CIs are based on the delta-method SEs of the back-transformed estimates, rather than on back-transforming the ends of the CIs. If you run the same `plot()` call without `comparisons = TRUE`, you will not get these negative bounds. and instead get the back-transformed intervals in *your* printed output.

I will consider whether this is adequately documented and/or there really is a way to handle this situation better. At the time I was coding it, it seemed unfathomable.

**Comment by guilhermeparreira** [comment]
Thank you @rvlenth ! I understand the problem! When I was reading the vignettes it was not clear to me (It would be nice to have a note "the CIs are based on the delta-method SEs of the back-transformed estimates" under the examples - I didn't read the methodology of your math to produce the comparison arrows -). I think that this method is fail-safe only if I use identity link then.

**Comment by rvlenth** [comment]
Well, I think I figured this out. Now, I always do everything on the link scale and back-transform later if that is called for. With a monotone transformation, the ranks do not change and hence the overlapping behaviors don't either.

```r
plot(l1, type = "r", comp = TRUE)
```
![image](https://user-images.githubusercontent.com/26777519/95137409-9b93a780-072d-11eb-9a43-c28edf5f2e6b.png)

This has the side effect (in many cases, at least) of making the comparison-arrow calculations more stable. For example, in your #228 example, we don't get an error with `by = "tipo"`

**Comment by rvlenth** [comment]
I believe this issue is resolved, so I am closing it. That does not keep you from following-up if you think there is more to do.

**Comment by guilhermeparreira** [comment]
Thank you @rvlenth !
I tried to used the `plot` with `comparisons=T` again, in other data set, but the comparisons arrows still don't follow the results from table (That's why you said "making the comparison-arrow calculations **more stable**"?).
The comparison arrows don't match with the table:
```
summary(pairs(l1), infer = c(T,T), type = "response", adjust = "sidak")[, -c(4,7)]
    plot(l1, 
         comparisons = T, 
         type = "response",
         int.adjust = "sidak",
         adjust = "sidak")
```
If you want, I can share the data with you

**Comment by rvlenth** [comment]
There is no way I can tell what may wrong based on your description. However, the fact that you have subsetted. the printed output is concerning because the sidak adjustment depends on the number of comparisons.

Maybe I don't need to see the data just yet. Can you show me:

(1) the results of confint(pairs(ll, adjust = "sidak")) -- every part of it including the annotations at the bottom;

(2) the results of confint(ll, type = "response", adjust = "sidak") -- again in total;

(3) the graphical results of plot(ll, type = "response", adjust = "sidak", comparisons = TRUE); and

(4) describe one or two specific places in the plot that you think disagree with the printed output.

Thanks

Sent from my iPad

On Oct 24, 2020, at 4:42 PM, Guilherme Parreira <notifications@github.com> wrote:

﻿

Thank you @rvlenth<https://github.com/rvlenth> !
I tried to used the plot with comparisons=T again, in other data set, but the comparisons arrows still don't follow the results from table (That's why you said "making the comparison-arrow calculations more stable"?).
The comparison arrows don't match with the table:

summary(pairs(l1), infer = c(T,T), type = "response", adjust = "sidak")[, -c(4,7)]
    plot(l1,
         comparisons = T,
         type = "response",
         int.adjust = "sidak",
         adjust = "sidak")


If you want, I can share the data with you

**Comment by rvlenth** [comment]
Oh, and

(5) Copy and paste any and all messages, warnings, or errors that occur in the above. Please start from scratch, so we are sure that ll has not changed in the course of these steps.

Sent from my iPad

On Oct 24, 2020, at 4:42 PM, Guilherme Parreira <notifications@github.com> wrote:

﻿

Thank you @rvlenth<https://github.com/rvlenth> !
I tried to used the plot with comparisons=T again, in other data set, but the comparisons arrows still don't follow the results from table (That's why you said "making the comparison-arrow calculations more stable"?).
The comparison arrows don't match with the table:

summary(pairs(l1), infer = c(T,T), type = "response", adjust = "sidak")[, -c(4,7)]
    plot(l1,
         comparisons = T,
         type = "response",
         int.adjust = "sidak",
         adjust = "sidak")


If you want, I can share the data with you

**Comment by guilhermeparreira** [comment]
hI @rvlenth !
It works! I don't know what I did wrong. Sorry for that.
