### ISSUE TITLE
regrid(transform="log") fails in the face of nonEst values

### ISSUE THREAD

**Issue by ekatko1** [rvlenth/emmeans#65]
Below is a reproducible example.
```
# Load factorial experiment dataset and add missing combination
df = npk
df = df[!( df$N==0 & df$P==1 & df$K==1),]
fit = lm( yield ~ N*P*K, data=df)
refgrid = emmeans(fit, ~ N*P*K)
newgrid = regrid(refgrid, transform = "log")
```
Non-positive response predictions are flagged as non-estimable
Error in object@V[incl, incl, drop = FALSE] : subscript out of bounds

Expected functioning: nonEst values should remain nonEst following a regrid.

PS: This is an awesome and super useful package, great work!!

**Comment by rvlenth** [comment]
Thanks for reporting this. Looking at my code, I see that I only considered cases where a grid point *becomes* non-estimable because its estimate is negative. It's going to be tricky to work with this, and I'm going to have to construct a test case where both situations occur to make sure I'm handling everything right. It may take awhile...

**Comment by rvlenth** [comment]
I think I have this fixed now. I've tested it with various combinations of existing non-estimable and negative estimates. The message about non-positive predictions is now only issued when it applies -- not for existing non-est cases.

**Comment by rvlenth** [comment]
I think this is resolved, so am closing the issue.

**Comment by ekatko1** [comment]
Great, didn't get a chance to test it with the holidays but thanks a lot
for the quick fix!

**Comment by ekatko1** [comment]
I just tested it again and it seems that the problem persists. The issue for me is that the following error pops up when a previously "nonEst" value is present in the refGrid prior to `regrid(transform="log")`:
`Error in object@V[incl, incl, drop = FALSE] : subscript out of bounds`

Best, 
Egor

**Comment by rvlenth** [comment]
Sorry for the delayed answer; I've been traveling.

I re-tested your example and I don't have a problem:

> # Load factorial experiment dataset and add missing combination
> df = npk
> df = df[!( df$N==0 & df$P==1 & df$K==1),]
> fit = lm( yield ~ N*P*K, data=df)
> refgrid = emmeans(fit, ~ N*P*K)
> summary(refgrid)
N P K emmean   SE df lower.CL upper.CL
0 0 0   51.4 3.38 14     44.2     58.7
1 0 0   63.8 3.38 14     56.5     71.0
0 1 0   54.3 3.38 14     47.1     61.6
1 1 0   57.9 3.38 14     50.7     65.2
0 0 1   52.0 3.38 14     44.7     59.3
1 0 1   54.7 3.38 14     47.4     61.9
0 1 1 nonEst   NA NA       NA       NA
1 1 1   54.4 3.38 14     47.1     61.6

Confidence level used: 0.95

> newgrid = regrid(refgrid, transform = "log")
> summary(newgrid)
N P K emmean     SE df lower.CL upper.CL
0 0 0   3.94 0.0658 14     3.80     4.08
1 0 0   4.16 0.0530 14     4.04     4.27
0 1 0   4.00 0.0622 14     3.86     4.13
1 1 0   4.06 0.0584 14     3.93     4.18
0 0 1   3.95 0.0650 14     3.81     4.09
1 0 1   4.00 0.0619 14     3.87     4.13
0 1 1 nonEst     NA NA       NA       NA
1 1 1   4.00 0.0622 14     3.86     4.13

Results are given on the log (not the response) scale.
Confidence level used: 0.95

I wonder if you did not install the update from github before you re-tested it.

The updated version of emmeans (1.3.2), which has the fix for this issue, is on CRAN as of this afternoon. It may take a day or two for the binary builds of it to become available.

**Comment by ekatko1** [comment]
No worries, sorry I should have mentioned that I had solved the problem and deleted my comment. I should have notified you that the problem had been resolved by restarting RStudio after I had installed emmeans from GitHub
